name: mki3dgame-snap # you probably want to 'snapcraft register <name>'
version: '1.17' # just for humans, typically '1.2+git' or '1.3.2'
summary: Searching for tokens in 3D stages amongst flying monsters. # 79 char long summary
description: |
  Search for tokens in 3D stages and avoid the monsters.
  See ' https://github.com/mki1967/mki3dgame ' for more info.
  (The stages are designed with MKI3D editor ' https://mki1967.github.io/mki3d/ ').

grade: stable # devel # must be 'stable' to release into candidate/stable channels
confinement: strict # devmode # use 'strict' once you have the right plugs and slots

apps:
  mki3dgame-snap:
    command: mki3dgame-snap-wrapper.bash
    # desktop: usr/share/applications/io.github.mki1967.mki3dgame.desktop # using: snap/gui/mki3dgame-snap.desktop
    plugs:
      - x11
      - opengl

parts:
  mki3dgame:
    # See 'snapcraft plugins'
    plugin: dump
    source: ./
    stage-packages:
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglew1.13
      # - zenity # zenity doesn't work in snap and increases snap size to 84152320 bytes
